//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RRHHModel", "FK_Vac_con_Cat_ConsumoVaciones", "Cat_ConsumoVaciones", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Acciones_RR_HH.Datos.Cat_ConsumoVaciones), "Vac_con", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Acciones_RR_HH.Datos.Vac_con), true)]
[assembly: EdmRelationshipAttribute("RRHHModel", "FK_Permisos_Empleados", "Empleados", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Acciones_RR_HH.Datos.Empleados), "Permisos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Acciones_RR_HH.Datos.Permisos), true)]
[assembly: EdmRelationshipAttribute("RRHHModel", "FK_Reg_entrada_salida_Empleados", "Empleados", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Acciones_RR_HH.Datos.Empleados), "Reg_entrada_salida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Acciones_RR_HH.Datos.Reg_entrada_salida), true)]
[assembly: EdmRelationshipAttribute("RRHHModel", "FK_Vac_con_Empleados", "Empleados", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Acciones_RR_HH.Datos.Empleados), "Vac_con", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Acciones_RR_HH.Datos.Vac_con), true)]
[assembly: EdmRelationshipAttribute("RRHHModel", "FK_Vacaciones_Acumuladas_Empleados", "Empleados", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Acciones_RR_HH.Datos.Empleados), "Vacaciones_Acumuladas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Acciones_RR_HH.Datos.Vacaciones_Acumuladas), true)]

#endregion

namespace Acciones_RR_HH.Datos
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SISTEMAEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SISTEMAEntities object using the connection string found in the 'SISTEMAEntities' section of the application configuration file.
        /// </summary>
        public SISTEMAEntities() : base("name=SISTEMAEntities", "SISTEMAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SISTEMAEntities object.
        /// </summary>
        public SISTEMAEntities(string connectionString) : base(connectionString, "SISTEMAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SISTEMAEntities object.
        /// </summary>
        public SISTEMAEntities(EntityConnection connection) : base(connection, "SISTEMAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cat_ConsumoVaciones> Cat_ConsumoVaciones
        {
            get
            {
                if ((_Cat_ConsumoVaciones == null))
                {
                    _Cat_ConsumoVaciones = base.CreateObjectSet<Cat_ConsumoVaciones>("Cat_ConsumoVaciones");
                }
                return _Cat_ConsumoVaciones;
            }
        }
        private ObjectSet<Cat_ConsumoVaciones> _Cat_ConsumoVaciones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Permisos> Permisos
        {
            get
            {
                if ((_Permisos == null))
                {
                    _Permisos = base.CreateObjectSet<Permisos>("Permisos");
                }
                return _Permisos;
            }
        }
        private ObjectSet<Permisos> _Permisos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reg_entrada_salida> Reg_entrada_salida
        {
            get
            {
                if ((_Reg_entrada_salida == null))
                {
                    _Reg_entrada_salida = base.CreateObjectSet<Reg_entrada_salida>("Reg_entrada_salida");
                }
                return _Reg_entrada_salida;
            }
        }
        private ObjectSet<Reg_entrada_salida> _Reg_entrada_salida;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vac_con> Vac_con
        {
            get
            {
                if ((_Vac_con == null))
                {
                    _Vac_con = base.CreateObjectSet<Vac_con>("Vac_con");
                }
                return _Vac_con;
            }
        }
        private ObjectSet<Vac_con> _Vac_con;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vacaciones_Acumuladas> Vacaciones_Acumuladas
        {
            get
            {
                if ((_Vacaciones_Acumuladas == null))
                {
                    _Vacaciones_Acumuladas = base.CreateObjectSet<Vacaciones_Acumuladas>("Vacaciones_Acumuladas");
                }
                return _Vacaciones_Acumuladas;
            }
        }
        private ObjectSet<Vacaciones_Acumuladas> _Vacaciones_Acumuladas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Empleados> Empleados
        {
            get
            {
                if ((_Empleados == null))
                {
                    _Empleados = base.CreateObjectSet<Empleados>("Empleados");
                }
                return _Empleados;
            }
        }
        private ObjectSet<Empleados> _Empleados;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cat_ConsumoVaciones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCat_ConsumoVaciones(Cat_ConsumoVaciones cat_ConsumoVaciones)
        {
            base.AddObject("Cat_ConsumoVaciones", cat_ConsumoVaciones);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Permisos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPermisos(Permisos permisos)
        {
            base.AddObject("Permisos", permisos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reg_entrada_salida EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReg_entrada_salida(Reg_entrada_salida reg_entrada_salida)
        {
            base.AddObject("Reg_entrada_salida", reg_entrada_salida);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vac_con EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVac_con(Vac_con vac_con)
        {
            base.AddObject("Vac_con", vac_con);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vacaciones_Acumuladas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVacaciones_Acumuladas(Vacaciones_Acumuladas vacaciones_Acumuladas)
        {
            base.AddObject("Vacaciones_Acumuladas", vacaciones_Acumuladas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Empleados EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmpleados(Empleados empleados)
        {
            base.AddObject("Empleados", empleados);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RRHHModel", Name="Cat_ConsumoVaciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cat_ConsumoVaciones : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cat_ConsumoVaciones object.
        /// </summary>
        /// <param name="idConsumoVaciones">Initial value of the IdConsumoVaciones property.</param>
        public static Cat_ConsumoVaciones CreateCat_ConsumoVaciones(global::System.Int32 idConsumoVaciones)
        {
            Cat_ConsumoVaciones cat_ConsumoVaciones = new Cat_ConsumoVaciones();
            cat_ConsumoVaciones.IdConsumoVaciones = idConsumoVaciones;
            return cat_ConsumoVaciones;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdConsumoVaciones
        {
            get
            {
                return _IdConsumoVaciones;
            }
            set
            {
                if (_IdConsumoVaciones != value)
                {
                    OnIdConsumoVacionesChanging(value);
                    ReportPropertyChanging("IdConsumoVaciones");
                    _IdConsumoVaciones = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdConsumoVaciones");
                    OnIdConsumoVacionesChanged();
                }
            }
        }
        private global::System.Int32 _IdConsumoVaciones;
        partial void OnIdConsumoVacionesChanging(global::System.Int32 value);
        partial void OnIdConsumoVacionesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripción
        {
            get
            {
                return _Descripción;
            }
            set
            {
                OnDescripciónChanging(value);
                ReportPropertyChanging("Descripción");
                _Descripción = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripción");
                OnDescripciónChanged();
            }
        }
        private global::System.String _Descripción;
        partial void OnDescripciónChanging(global::System.String value);
        partial void OnDescripciónChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Vac_con_Cat_ConsumoVaciones", "Vac_con")]
        public EntityCollection<Vac_con> Vac_con
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vac_con>("RRHHModel.FK_Vac_con_Cat_ConsumoVaciones", "Vac_con");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vac_con>("RRHHModel.FK_Vac_con_Cat_ConsumoVaciones", "Vac_con", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RRHHModel", Name="Empleados")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empleados : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Empleados object.
        /// </summary>
        /// <param name="iDEmpleado">Initial value of the IDEmpleado property.</param>
        /// <param name="nombres">Initial value of the Nombres property.</param>
        /// <param name="apellidos">Initial value of the Apellidos property.</param>
        /// <param name="edad">Initial value of the Edad property.</param>
        /// <param name="sexo">Initial value of the Sexo property.</param>
        /// <param name="estadoCivil">Initial value of the EstadoCivil property.</param>
        public static Empleados CreateEmpleados(global::System.String iDEmpleado, global::System.String nombres, global::System.String apellidos, global::System.String edad, global::System.Boolean sexo, global::System.Int32 estadoCivil)
        {
            Empleados empleados = new Empleados();
            empleados.IDEmpleado = iDEmpleado;
            empleados.Nombres = nombres;
            empleados.Apellidos = apellidos;
            empleados.Edad = edad;
            empleados.Sexo = sexo;
            empleados.EstadoCivil = estadoCivil;
            return empleados;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDEmpleado
        {
            get
            {
                return _IDEmpleado;
            }
            set
            {
                if (_IDEmpleado != value)
                {
                    OnIDEmpleadoChanging(value);
                    ReportPropertyChanging("IDEmpleado");
                    _IDEmpleado = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IDEmpleado");
                    OnIDEmpleadoChanged();
                }
            }
        }
        private global::System.String _IDEmpleado;
        partial void OnIDEmpleadoChanging(global::System.String value);
        partial void OnIDEmpleadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdDocumentos
        {
            get
            {
                return _IdDocumentos;
            }
            set
            {
                OnIdDocumentosChanging(value);
                ReportPropertyChanging("IdDocumentos");
                _IdDocumentos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdDocumentos");
                OnIdDocumentosChanged();
            }
        }
        private Nullable<global::System.Int32> _IdDocumentos;
        partial void OnIdDocumentosChanging(Nullable<global::System.Int32> value);
        partial void OnIdDocumentosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombres
        {
            get
            {
                return _Nombres;
            }
            set
            {
                OnNombresChanging(value);
                ReportPropertyChanging("Nombres");
                _Nombres = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombres");
                OnNombresChanged();
            }
        }
        private global::System.String _Nombres;
        partial void OnNombresChanging(global::System.String value);
        partial void OnNombresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellidos
        {
            get
            {
                return _Apellidos;
            }
            set
            {
                OnApellidosChanging(value);
                ReportPropertyChanging("Apellidos");
                _Apellidos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellidos");
                OnApellidosChanged();
            }
        }
        private global::System.String _Apellidos;
        partial void OnApellidosChanging(global::System.String value);
        partial void OnApellidosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Edad
        {
            get
            {
                return _Edad;
            }
            set
            {
                OnEdadChanging(value);
                ReportPropertyChanging("Edad");
                _Edad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Edad");
                OnEdadChanged();
            }
        }
        private global::System.String _Edad;
        partial void OnEdadChanging(global::System.String value);
        partial void OnEdadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.Boolean _Sexo;
        partial void OnSexoChanging(global::System.Boolean value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EstadoCivil
        {
            get
            {
                return _EstadoCivil;
            }
            set
            {
                OnEstadoCivilChanging(value);
                ReportPropertyChanging("EstadoCivil");
                _EstadoCivil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EstadoCivil");
                OnEstadoCivilChanged();
            }
        }
        private global::System.Int32 _EstadoCivil;
        partial void OnEstadoCivilChanging(global::System.Int32 value);
        partial void OnEstadoCivilChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Permisos_Empleados", "Permisos")]
        public EntityCollection<Permisos> Permisos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Permisos>("RRHHModel.FK_Permisos_Empleados", "Permisos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Permisos>("RRHHModel.FK_Permisos_Empleados", "Permisos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Reg_entrada_salida_Empleados", "Reg_entrada_salida")]
        public EntityCollection<Reg_entrada_salida> Reg_entrada_salida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reg_entrada_salida>("RRHHModel.FK_Reg_entrada_salida_Empleados", "Reg_entrada_salida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reg_entrada_salida>("RRHHModel.FK_Reg_entrada_salida_Empleados", "Reg_entrada_salida", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Vac_con_Empleados", "Vac_con")]
        public EntityCollection<Vac_con> Vac_con
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vac_con>("RRHHModel.FK_Vac_con_Empleados", "Vac_con");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vac_con>("RRHHModel.FK_Vac_con_Empleados", "Vac_con", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Vacaciones_Acumuladas_Empleados", "Vacaciones_Acumuladas")]
        public EntityCollection<Vacaciones_Acumuladas> Vacaciones_Acumuladas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vacaciones_Acumuladas>("RRHHModel.FK_Vacaciones_Acumuladas_Empleados", "Vacaciones_Acumuladas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vacaciones_Acumuladas>("RRHHModel.FK_Vacaciones_Acumuladas_Empleados", "Vacaciones_Acumuladas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RRHHModel", Name="Permisos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Permisos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Permisos object.
        /// </summary>
        /// <param name="idPermiso">Initial value of the IdPermiso property.</param>
        public static Permisos CreatePermisos(global::System.Int32 idPermiso)
        {
            Permisos permisos = new Permisos();
            permisos.IdPermiso = idPermiso;
            return permisos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPermiso
        {
            get
            {
                return _IdPermiso;
            }
            set
            {
                if (_IdPermiso != value)
                {
                    OnIdPermisoChanging(value);
                    ReportPropertyChanging("IdPermiso");
                    _IdPermiso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPermiso");
                    OnIdPermisoChanged();
                }
            }
        }
        private global::System.Int32 _IdPermiso;
        partial void OnIdPermisoChanging(global::System.Int32 value);
        partial void OnIdPermisoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdEmpleado
        {
            get
            {
                return _IdEmpleado;
            }
            set
            {
                OnIdEmpleadoChanging(value);
                ReportPropertyChanging("IdEmpleado");
                _IdEmpleado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdEmpleado");
                OnIdEmpleadoChanged();
            }
        }
        private global::System.String _IdEmpleado;
        partial void OnIdEmpleadoChanging(global::System.String value);
        partial void OnIdEmpleadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaIni
        {
            get
            {
                return _FechaIni;
            }
            set
            {
                OnFechaIniChanging(value);
                ReportPropertyChanging("FechaIni");
                _FechaIni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaIni");
                OnFechaIniChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaIni;
        partial void OnFechaIniChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaIniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFin
        {
            get
            {
                return _FechaFin;
            }
            set
            {
                OnFechaFinChanging(value);
                ReportPropertyChanging("FechaFin");
                _FechaFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFin");
                OnFechaFinChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFin;
        partial void OnFechaFinChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Comprobante
        {
            get
            {
                return StructuralObject.GetValidValue(_Comprobante);
            }
            set
            {
                OnComprobanteChanging(value);
                ReportPropertyChanging("Comprobante");
                _Comprobante = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comprobante");
                OnComprobanteChanged();
            }
        }
        private global::System.Byte[] _Comprobante;
        partial void OnComprobanteChanging(global::System.Byte[] value);
        partial void OnComprobanteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Permisos_Empleados", "Empleados")]
        public Empleados Empleados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Permisos_Empleados", "Empleados").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Permisos_Empleados", "Empleados").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empleados> EmpleadosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Permisos_Empleados", "Empleados");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empleados>("RRHHModel.FK_Permisos_Empleados", "Empleados", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RRHHModel", Name="Reg_entrada_salida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reg_entrada_salida : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reg_entrada_salida object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="iDEmpleado">Initial value of the IDEmpleado property.</param>
        public static Reg_entrada_salida CreateReg_entrada_salida(global::System.Int32 id, global::System.String iDEmpleado)
        {
            Reg_entrada_salida reg_entrada_salida = new Reg_entrada_salida();
            reg_entrada_salida.id = id;
            reg_entrada_salida.IDEmpleado = iDEmpleado;
            return reg_entrada_salida;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDEmpleado
        {
            get
            {
                return _IDEmpleado;
            }
            set
            {
                OnIDEmpleadoChanging(value);
                ReportPropertyChanging("IDEmpleado");
                _IDEmpleado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IDEmpleado");
                OnIDEmpleadoChanged();
            }
        }
        private global::System.String _IDEmpleado;
        partial void OnIDEmpleadoChanging(global::System.String value);
        partial void OnIDEmpleadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Entrada
        {
            get
            {
                return _Entrada;
            }
            set
            {
                OnEntradaChanging(value);
                ReportPropertyChanging("Entrada");
                _Entrada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Entrada");
                OnEntradaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Entrada;
        partial void OnEntradaChanging(Nullable<global::System.DateTime> value);
        partial void OnEntradaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Salida
        {
            get
            {
                return _Salida;
            }
            set
            {
                OnSalidaChanging(value);
                ReportPropertyChanging("Salida");
                _Salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salida");
                OnSalidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Salida;
        partial void OnSalidaChanging(Nullable<global::System.DateTime> value);
        partial void OnSalidaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Reg_entrada_salida_Empleados", "Empleados")]
        public Empleados Empleados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Reg_entrada_salida_Empleados", "Empleados").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Reg_entrada_salida_Empleados", "Empleados").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empleados> EmpleadosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Reg_entrada_salida_Empleados", "Empleados");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empleados>("RRHHModel.FK_Reg_entrada_salida_Empleados", "Empleados", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RRHHModel", Name="Vac_con")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vac_con : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vac_con object.
        /// </summary>
        /// <param name="idVC">Initial value of the IdVC property.</param>
        public static Vac_con CreateVac_con(global::System.Int32 idVC)
        {
            Vac_con vac_con = new Vac_con();
            vac_con.IdVC = idVC;
            return vac_con;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdVC
        {
            get
            {
                return _IdVC;
            }
            set
            {
                if (_IdVC != value)
                {
                    OnIdVCChanging(value);
                    ReportPropertyChanging("IdVC");
                    _IdVC = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdVC");
                    OnIdVCChanged();
                }
            }
        }
        private global::System.Int32 _IdVC;
        partial void OnIdVCChanging(global::System.Int32 value);
        partial void OnIdVCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdEmpleado
        {
            get
            {
                return _IdEmpleado;
            }
            set
            {
                OnIdEmpleadoChanging(value);
                ReportPropertyChanging("IdEmpleado");
                _IdEmpleado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdEmpleado");
                OnIdEmpleadoChanged();
            }
        }
        private global::System.String _IdEmpleado;
        partial void OnIdEmpleadoChanging(global::System.String value);
        partial void OnIdEmpleadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DiasConsumidos
        {
            get
            {
                return _DiasConsumidos;
            }
            set
            {
                OnDiasConsumidosChanging(value);
                ReportPropertyChanging("DiasConsumidos");
                _DiasConsumidos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiasConsumidos");
                OnDiasConsumidosChanged();
            }
        }
        private Nullable<global::System.Double> _DiasConsumidos;
        partial void OnDiasConsumidosChanging(Nullable<global::System.Double> value);
        partial void OnDiasConsumidosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idConsumovaciones
        {
            get
            {
                return _idConsumovaciones;
            }
            set
            {
                OnidConsumovacionesChanging(value);
                ReportPropertyChanging("idConsumovaciones");
                _idConsumovaciones = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idConsumovaciones");
                OnidConsumovacionesChanged();
            }
        }
        private Nullable<global::System.Int32> _idConsumovaciones;
        partial void OnidConsumovacionesChanging(Nullable<global::System.Int32> value);
        partial void OnidConsumovacionesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Vac_con_Cat_ConsumoVaciones", "Cat_ConsumoVaciones")]
        public Cat_ConsumoVaciones Cat_ConsumoVaciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cat_ConsumoVaciones>("RRHHModel.FK_Vac_con_Cat_ConsumoVaciones", "Cat_ConsumoVaciones").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cat_ConsumoVaciones>("RRHHModel.FK_Vac_con_Cat_ConsumoVaciones", "Cat_ConsumoVaciones").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cat_ConsumoVaciones> Cat_ConsumoVacionesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cat_ConsumoVaciones>("RRHHModel.FK_Vac_con_Cat_ConsumoVaciones", "Cat_ConsumoVaciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cat_ConsumoVaciones>("RRHHModel.FK_Vac_con_Cat_ConsumoVaciones", "Cat_ConsumoVaciones", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Vac_con_Empleados", "Empleados")]
        public Empleados Empleados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Vac_con_Empleados", "Empleados").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Vac_con_Empleados", "Empleados").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empleados> EmpleadosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Vac_con_Empleados", "Empleados");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empleados>("RRHHModel.FK_Vac_con_Empleados", "Empleados", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RRHHModel", Name="Vacaciones_Acumuladas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vacaciones_Acumuladas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vacaciones_Acumuladas object.
        /// </summary>
        /// <param name="id_Va">Initial value of the Id_Va property.</param>
        public static Vacaciones_Acumuladas CreateVacaciones_Acumuladas(global::System.Int32 id_Va)
        {
            Vacaciones_Acumuladas vacaciones_Acumuladas = new Vacaciones_Acumuladas();
            vacaciones_Acumuladas.Id_Va = id_Va;
            return vacaciones_Acumuladas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Va
        {
            get
            {
                return _Id_Va;
            }
            set
            {
                if (_Id_Va != value)
                {
                    OnId_VaChanging(value);
                    ReportPropertyChanging("Id_Va");
                    _Id_Va = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Va");
                    OnId_VaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Va;
        partial void OnId_VaChanging(global::System.Int32 value);
        partial void OnId_VaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdEmpleado
        {
            get
            {
                return _IdEmpleado;
            }
            set
            {
                OnIdEmpleadoChanging(value);
                ReportPropertyChanging("IdEmpleado");
                _IdEmpleado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdEmpleado");
                OnIdEmpleadoChanged();
            }
        }
        private global::System.String _IdEmpleado;
        partial void OnIdEmpleadoChanging(global::System.String value);
        partial void OnIdEmpleadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Dias
        {
            get
            {
                return _Dias;
            }
            set
            {
                OnDiasChanging(value);
                ReportPropertyChanging("Dias");
                _Dias = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dias");
                OnDiasChanged();
            }
        }
        private Nullable<global::System.Double> _Dias;
        partial void OnDiasChanging(Nullable<global::System.Double> value);
        partial void OnDiasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Pagadas
        {
            get
            {
                return _Pagadas;
            }
            set
            {
                OnPagadasChanging(value);
                ReportPropertyChanging("Pagadas");
                _Pagadas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pagadas");
                OnPagadasChanged();
            }
        }
        private Nullable<global::System.Boolean> _Pagadas;
        partial void OnPagadasChanging(Nullable<global::System.Boolean> value);
        partial void OnPagadasChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RRHHModel", "FK_Vacaciones_Acumuladas_Empleados", "Empleados")]
        public Empleados Empleados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Vacaciones_Acumuladas_Empleados", "Empleados").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Vacaciones_Acumuladas_Empleados", "Empleados").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empleados> EmpleadosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleados>("RRHHModel.FK_Vacaciones_Acumuladas_Empleados", "Empleados");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empleados>("RRHHModel.FK_Vacaciones_Acumuladas_Empleados", "Empleados", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
